

f= open('song.txt','w')
f.write('Stronger, Kanye 2007 - Hip Hop/Rap\n')
f.write('Baby Love, Supremes  - R&B/Soul\n')
f.write('Delicate, Taylor Swift - Pop\n')
f.write('Clint Eastwood, Gorillaz - Rock\n')
f.write('Pancho and Lefty, Townes Van Zandt  - Country\n')
f.write('Truth Hurts, Lizzo 2017 - Pop\n')
f.write('Without You, Nilsson, - Classic Rock\n')
f.write('JAPAN, Famous Dex - Hip Hop/Rap\n')
f.write('Six Feet under, Billie Eilish - Alternative/Indie\n')
f.write('You’re So Vain, Carly Simon - Rock\n')
f.write('Time After Time, Cyndi Lauper - Rock\n')
f.write('Where Is My Mind, The Pixies - Alternative/Indie\n')
f.write('So What, Miles Davis - Jazz\n')
f.write('Welcome to the Jungle, Guns ‘n’ Roses - Rock\n')
f.write('Old Town Road, Lil Nas X - Hip Hop/Rap\n')

f.close()
